#!/bin/bash

CURDIR=`pwd`
OLDGOPATH="$GOPATH"
export GOPATH="$OLDGOPATH":"$CURDIR"

#gofmt -w src

go install frm_server
cp -r src/frm_server/*.cfg bin/

go install frm_client
cp -r src/frm_client/*.cfg bin/


export GOPATH="$OLDGOPATH"

echo 'finished'
