#!/bin/bash

CURDIR=`pwd`
OLDGOPATH="$GOPATH"
export GOPATH="$OLDGOPATH":"$CURDIR"

#gofmt -w src

go install frmServer
cp -r src/frmServer/*.cfg bin/

go install frmClient
cp -r src/frmClient/*.cfg bin/


export GOPATH="$OLDGOPATH"

echo 'finished'
